; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny1614]
platform = atmelmegaavr
board = ATtiny1614
framework = arduino
; This option doesn’t make any changes to real clock settings on hardware. Just informs the software of my desired clock freq
board_build.f_cpu=20000000L
;build_flags = -I$PROJECT_PACKAGES_DIR/toolchain-atmelavr/avr/include

; SerialUPDI Settings
upload_protocol = serialupdi
upload_speed = 115200
upload_port = /dev/cu.wchusbserial14540

; Monitor Settings (Replaces the 'screen' command)
monitor_speed = 115200
monitor_port = /dev/cu.wchusbserial14540

; dont erase updates to the eeprom where im saving config stuff. these two set the clock speed at 20MHz
board_fuses.eesave = yes
board_fuses.OSCCFG = 0x02